name: rtd
dependencies:
- appdirs=1.4.0=py35_0
- backports.shutil_get_terminal_size=1.0.0=py35_0
- blas=1.1=openblas
- cairo=1.12.18=8
- click=6.6=py35_0
- click-plugins=1.0.3=py35_0
- cligj=0.4.0=py35_0
- curl=7.49.1=1
- cycler=0.10.0=py35_0
- cython=0.24.1=py35_0
- decorator=4.0.10=py35_0
- docopt=0.6.2=py35_0
- entrypoints=0.2.2=py35_0
- expat=2.1.0=2
- fasteners=0.14.1=py35_1
- fiona=1.7.0=np111py35_2
- flask=0.11.1=py35_0
- fontconfig=2.11.1=3
- freetype=2.6.3=1
- freexl=1.0.2=1
- future=0.15.2=py35_0
- gdal=2.1.1=np111py35_3
- geos=3.4.2=2
- gettext=0.19.7=1
- giflib=5.1.4=0
- glib=2.48.0=4
- harfbuzz=1.0.6=0
- hdf4=4.2.12=0
- hdf5=1.8.17=6
- icu=56.1=4
- ipykernel=4.5.0=py35_0
- ipython=5.1.0=py35_0
- ipython-notebook=4.0.4=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=5.2.2=py35_2
- itsdangerous=0.24=py35_0
- jinja2=2.8=py35_1
- jpeg=9b=0
- json-c=0.12=0
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.4.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_core=4.2.0=py35_0
- kealib=1.4.6=3
- libdap4=3.18.0=2
- libffi=3.2.1=2
- libgfortran=3.0.0=1
- libiconv=1.14=3
- libnetcdf=4.4.1=0
- libpng=1.6.24=0
- libpq=9.5.4=2
- libsodium=1.0.10=0
- libspatialite=4.3.0a=9
- libtiff=4.0.6=6
- libuuid=1.0.3=1
- libxml2=2.9.4=0
- libxslt=1.1.29=1
- lxml=3.6.4=py35_0
- markupsafe=0.23=py35_2
- matplotlib=1.5.3=np111py35_0
- mistune=0.7.3=py35_0
- monotonic=1.1=py35_0
- munch=2.0.4=py35_0
- nbconvert=4.2.0=py35_0
- nbformat=4.1.0=py35_0
- ncurses=5.9=9
- nose=1.3.7=py35_2
- notebook=4.2.3=py35_0
- numpy=1.11.2=py35_blas_openblas_200
- openblas=0.2.18=5
- openjpeg=2.1.0=6
- openssl=1.0.2j=0
- pango=1.40.1=0
- path.py=8.2.1=py35_0
- pcre=8.39=0
- pexpect=4.2.1=py35_0
- pickleshare=0.7.4=py35_0
- pip=8.1.2=py35_0
- pixman=0.32.6=0
- proj.4=4.9.2=0
- prompt_toolkit=1.0.7=py35_0
- psutil=4.3.1=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.1.3=py35_1
- pyparsing=2.1.9=py35_0
- pyqt=4.11.4=py35_4
- python=3.5.2=2
- python-dateutil=2.5.3=py35_0
- pytz=2016.7=py35_0
- pyzmq=15.4.0=py35_0
- qt=4.8.7=4
- qtconsole=4.2.1=py35_0
- readline=6.2=2
- requests=2.11.1=py35_0
- scipy=0.18.1=np111py35_blas_openblas_200
- setuptools=27.2.0=py35_0
- shapely=1.5.17=np111py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=1
- terminado=0.6=py35_0
- tk=8.5.19=0
- tornado=4.4.2=py35_0
- traitlets=4.3.1=py35_0
- unicodecsv=0.14.1=py35_0
- unidecode=0.04.19=py35_0
- wcwidth=0.1.7=py35_0
- werkzeug=0.11.11=py35_0
- wheel=0.29.0=py35_0
- whoosh=2.7.4=py35_0
- widgetsnbextension=1.2.6=py35_3
- wrapt=1.10.8=py35_0
- xerces-c=3.1.4=2
- xlrd=1.0.0=py35_0
- xlsxwriter=0.9.3=py35_0
- xz=5.2.2=0
- zeromq=4.1.5=0
- zlib=1.2.8=3
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - prompt-toolkit==1.0.7

